name: skaletek_kyc_flutter
version: 1.0.0

description: >-
  A Flutter SDK for integrating Skaletek's Know Your Customer (KYC) verification services. Supports document upload, face liveness, and customizable UI.

homepage: https://github.com/your-org/skaletek-kyc-flutter
repository: https://github.com/your-org/skaletek-kyc-flutter
issue_tracker: https://github.com/your-org/skaletek-kyc-flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.1.0
  amplify_flutter: ^1.0.0
  image_picker: ^1.0.0
  permission_handler: ^11.0.0
  # Add any other dependencies your SDK needs

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.yourorg.skaletek_kyc_flutter
        pluginClass: SkaletekKycFlutterPlugin
      ios:
        pluginClass: SkaletekKycFlutterPlugin
  assets:
    - assets/images/

# Exclude example and test from the published package
publish_to: 'https://pub.dev/'
